# Generated by Django 2.2 on 2021-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_auto_20210815_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
