# Generated by Django 2.2 on 2021-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
