# Generated by Django 2.2 on 2021-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_patient_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doc_seen',
            field=models.BooleanField(default=False),
        ),
    ]
