# Generated by Django 2.2 on 2021-08-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_patient_doc_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ailment',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
